/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.legalai.service; import jakarta.validation.constraints.*; import org.springframework.stereotype.Service; import java.util.*; /**
                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                  */
@Service public class ContractReviewService { /**
                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                */
public record Request(@NotBlank String contractName,@Positive long amount,boolean autoRenewal,boolean unlimitedLiability,boolean personalData,boolean foreignLaw){} /**
                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                    */
public record Result(String contractName,int riskScore,String level,List<String> findings,List<String> requiredActions){} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public Result review(Request r){int score=r.amount()>1000000?25:10;var f=new ArrayList<String>();var a=new ArrayList<String>();if(r.autoRenewal()){score+=15;f.add("存在自动续约条款");a.add("补充续约提醒与退出窗口");}if(r.unlimitedLiability()){score+=35;f.add("存在无限责任");a.add("提交重大责任条款审批");}if(r.personalData()){score+=15;f.add("涉及个人信息处理");a.add("补充数据处理附件");}if(r.foreignLaw()){score+=15;f.add("适用境外法律");a.add("由外部律师复核适用法与争议解决");}return new Result(r.contractName(),Math.min(100,score),score>=70?"HIGH":score>=40?"MEDIUM":"LOW",f,a);} }
