/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.legalai.controller; import cn.zhuatech.legalai.common.ApiResponse; import cn.zhuatech.legalai.service.ContractReviewService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; /**
                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                      */
@RestController @RequestMapping("/api/ai") @PreAuthorize("hasAnyRole('DOMAIN_USER','DOMAIN_OPERATOR','ADMIN')") public class AiFeatureController { private final ContractReviewService service; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public AiFeatureController(ContractReviewService service){this.service=service;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/contract/review") public ApiResponse<ContractReviewService.Result> execute(@Valid @RequestBody ContractReviewService.Request request){return ApiResponse.ok("合同条款风险预审完成",service.review(request));} }